defaults:
  - dataset: WN18RR
  - _self_

# 项目目录
project_dir: D:\GitHub\TCRA
# 数据集目录
dataset_dir: ${project_dir}\data\dataset
# 每个数据集的输出目录
output_dir: ${project_dir}\outputs\\${dataset}

# 支持的数据集列表
dataset_list: [WN18RR, FB15k_237, Kinship]

# embedding 100-500
# 模型配置
model: TCRA
model_list:
  - TCRA

# TODO 全局的配置
epoch: 10 # 训练轮数
batch_size: 16 # 批次大小
# learning_rate: 1.5e-3 # 学习率
# h_dim: 200 # 节点维度
# pred_rel_w: true # 是否使用关系权重预测
# label_smooth: 0.1 # 标签平滑
s_dim: 200 # 全局节点表示维度
decoder: ConvE # 解码器类型 [TransE, DistMult, ConvE]
# TODO 训练配置
device: 0 # 训练设备 cuda
warmup_epoch: 5 # 预热轮数
max_no_improve: 10 # 早停轮数
cpu_worker_num: 6 # 数据加载线程数

# TODO graph配置
kg_layer: 2 # 知识图谱GNN层数
# rm_rate: 0.0 # 边移除率
# ent_drop: 0.2 # 实体嵌入dropout
# rel_drop: 0.2 # 关系嵌入dropout
# comp_op: mul # 组合操作 [add, mul]
# bn: true # 是否使用批归一化

# TODO 规则配置
rule_dim: 200 # 规则嵌入维度
rule_hidden_dim: 200 # 规则层隐藏维度
rule_heads: 2 # 规则注意力头数
rule_layers: 4 # 规则Transformer层数
rule_drop: 0.1 # 规则层dropout率
rule_len: 10 # 规则最大长度
# TODO 不清楚
rules_num: 3000 # 规则数量 7382个规则体 1000-7000
num_encoder: 2 # 规则编码器层数 【2-7】

# TODO decoder ConvE配置
# ConvE输入2d维度 k_h * k_w = h_dim
k_h: 10
k_w: 20
# conv_drop: 0.1 # ConvE卷积层dropout
# ent_drop_pred: 0.1 # 实体预测dropout
# fc_drop: 0.1 # 全连接层dropout
# ker_sz: 3 # ConvE解码器卷积核大小
# out_channel: 32 # ConvE解码器输出通道数
# TransE边界参数gamma
# 边界参数，帮助模型区分正负样本的距离
gamma: 12

# Hydra配置
hydra:
  job:
    chdir: false # 保持当前的工作目录行为
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S} # 输出目录
  sweep:
    dir: ${output_dir}/sweep/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}
